<?php

namespace ContainerDsHrvj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_TranslationDebugService extends srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'console.command.translation_debug' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['console.command.translation_debug'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand(($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->privates['translation.reader'] ?? $container->load('getTranslation_ReaderService')), ($container->privates['translation.extractor'] ?? $container->load('getTranslation_ExtractorService')), (\dirname(__DIR__, 4).'/translations'), '', [], [0 => '/home/francisco/dev/ddd_in_php_from_zero/vendor/symfony/http-kernel/EventListener/LocaleAwareListener.php', 1 => '/home/francisco/dev/ddd_in_php_from_zero/vendor/symfony/framework-bundle/Command/TranslationDebugCommand.php', 2 => '/home/francisco/dev/ddd_in_php_from_zero/vendor/symfony/framework-bundle/CacheWarmer/TranslationsCacheWarmer.php']);

        $instance->setName('debug:translation');

        return $instance;
    }
}
