<?php

namespace ContainerDsHrvj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'MN\Apps\Ddd\Backend\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \MN\Apps\Ddd\Backend\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';

        return $container->services['MN\\Apps\\Ddd\\Backend\\Controller\\HealthCheck\\HealthCheckGetController'] = new \MN\Apps\Ddd\Backend\Controller\HealthCheck\HealthCheckGetController();
    }
}
