<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsHrvj6\srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsHrvj6/srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDsHrvj6.legacy');

    return;
}

if (!\class_exists(srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDsHrvj6\srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer::class, srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer::class, false);
}

return new \ContainerDsHrvj6\srcMN_Apps_Ddd_Backend_DddBackendKernelTestDebugContainer([
    'container.build_hash' => 'DsHrvj6',
    'container.build_id' => '7606fb78',
    'container.build_time' => 1594950970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsHrvj6');
